import Head from 'next/head'
import Image from 'next/image'
import CoinList from '../Components/CoinList'
import SearchBar from '../Components/SearchBar'

export default function Home({filteredCoins}) {
  return (
    <div>
      <Head>
        <title>Learn next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <SearchBar type="text" placeholder="Search"/>
     <CoinList filteredCoins={filteredCoins}/>
    </div>
  )
}

export const getServerSideProps = async () => {
  const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false')
  const filteredCoins = await res.json()
  return{
    props:{
      filteredCoins
    }
  }
}